export const SET_USER = "SET_USER";
export const SET_EVENTS = "SET_EVENTS";
export const SET_EVENTS_LOADING = "SET_EVENTS_LOADING";
export const SET_ORGANIZED_EVENTS = "SET_ORGANIZED_EVENTS";
export const SET_ORGANIZED_LOADING = "SET_ORGANIZED_LOADING";
